"""Armory-research consumer bot.

The single producer of armory playbook-gap tasks for the factory. It does NOT
perform gap analysis itself — that lives in Molly's ``molly.armory.research``
module, which owns the canonical vulnerability-class taxonomy and computes
armory coverage from ``PlaybookLoader`` (not regex on a frontmatter field).
This bot:

  1. pulls normalized, armory-deduped findings from that module,
  2. drops any whose target playbook already has an OPEN factory task — dedup
     on the stable ``artifact_path`` key, never on a date/report-id-stamped
     page name, and
  3. creates one ``Task_Playbook_*`` page per remaining finding, assigned to
     the factory with ``skip_decomposition: true`` so a grinder picks it up.

This replaces the gap analysis that previously lived in two divergent places —
this orchestrator's ``class-gap-researcher`` and Molly's ``h1_researcher`` —
each with its own coverage model and taxonomy, which is what produced
duplicate playbook tasks (e.g. repeatedly re-filing ``other-generic.md``).

Findings are consumed as plain dicts matching the agreed ``ArmoryGapFinding``
schema; the fetch transport is isolated in ``_fetch_findings`` so the pull
mechanism (co-located CLI vs. a fetched JSON artifact) can change without
touching the bot logic.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import shlex
import time
from datetime import datetime, timezone
from typing import Any

from ..config import get_settings
from ..integrations.meshwiki_client import MeshWikiClient
from .base import BaseBot, BotResult

logger = logging.getLogger(__name__)

# Task statuses that mean "a task for this playbook is already in flight" — a
# finding whose artifact_path matches one of these must not be re-filed.
_OPEN_STATUSES = ("planned", "in_progress", "review")

_REQUIRED_KEYS = ("vuln_class", "artifact_path", "scope", "title")


def _sanitize(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", s)


def _page_name(finding: dict) -> str:
    """Stable, collision-free task page name derived from the finding identity.

    Deliberately contains NO date or report id, so a re-run for the same
    uncovered class maps to the same page name and can never create a
    duplicate (belt-and-suspenders alongside the open-queue dedup).
    """
    vuln = _sanitize(finding["vuln_class"])
    scope = _sanitize(finding.get("scope") or "generic")
    target = finding.get("target")
    if target:
        return f"Task_Playbook_{_sanitize(target)}_{vuln}_{scope}"
    return f"Task_Playbook_{vuln}_{scope}"


def _render_task_page(finding: dict, armory_repo: str) -> tuple[str, str]:
    """Render the MeshWiki task page for a finding. Returns (page_name, content)."""
    page_name = _page_name(finding)
    artifact_path = finding["artifact_path"]
    repo_root = artifact_path.split("/", 1)[0] if "/" in artifact_path else "playbooks"
    vuln = finding["vuln_class"]
    scope = finding.get("scope") or "generic"
    title = finding["title"]
    severity = finding.get("severity") or "unknown"
    source = finding.get("source") or "unknown"
    rationale = finding.get("rationale") or "(no rationale)"
    detail = finding.get("detail")
    target = finding.get("target")
    evidence = finding.get("evidence") or []

    tags = ["playbook", "armory-research", scope, _sanitize(vuln)]
    frontmatter = (
        "---\n"
        "type: task\n"
        "assignee: factory\n"
        "status: planned\n"
        f'title: "{title}"\n'
        f"repo: {armory_repo}\n"
        f"repo_root: {repo_root}\n"
        "artifact_type: playbook\n"
        "skip_decomposition: true\n"
        # Stable dedup key read back by _open_artifact_paths on the next run.
        f"playbook_path: {artifact_path}\n"
        f"vulnerability_class: {vuln}\n"
        f"scope: {scope}\n"
        + (f"target: {target}\n" if target else "")
        + f"severity: {severity}\n"
        f"source: {source}\n"
        f"tags: [{', '.join(tags)}]\n"
        "estimation: m\n"
        "---\n\n"
        "<<TaskStatus>>\n\n"
    )

    ref_lines = []
    for ev in evidence:
        ref = ev.get("ref") or ev.get("url") or "reference"
        url = ev.get("url")
        ev_title = ev.get("title")
        label = f"{ref}" + (f" — {ev_title}" if ev_title else "")
        ref_lines.append(f"- {f'[{label}]({url})' if url else label}")
    references = "\n".join(ref_lines) if ref_lines else "- (none provided)"

    body = (
        f"# {title}\n\n"
        "## Context\n\n"
        "Generated by the **armory-research** bot from a finding produced by "
        "Molly's `molly.armory.research` module (one canonical taxonomy; "
        "coverage computed from the armory, so this class is a genuine gap).\n\n"
        f"**Vulnerability class:** `{vuln}`\n"
        f"**Scope:** {scope}\n"
        + (f"**Target:** {target}\n" if target else "")
        + f"**Severity:** {severity}\n"
        f"**Source:** {source}\n"
        f"**Created:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n"
        "## Why This Is a Gap\n\n"
        f"{rationale}\n\n"
        + (f"## Detail\n\n{detail}\n\n" if detail else "")
        + "## Deliverable\n\n"
        f"Create `{artifact_path}` in `{armory_repo}` — a {scope} playbook for "
        f"`{vuln}` using the strict Molly schema (frontmatter `playbook`, "
        "`name`, `leaf_type`, `scope`, `applies_to`, `checks`; NOT body fenced "
        "blocks). Include `vulnerability_class` in the frontmatter.\n\n"
        "## Acceptance Criteria\n\n"
        f"- [ ] Playbook at `{artifact_path}` lints clean via "
        "`PlaybookLoader.load_all()`\n"
        f"- [ ] Frontmatter carries `scope: {scope}`"
        + (f" and `target: {target}`" if target else "")
        + f" and `vulnerability_class: {vuln}`\n"
        "- [ ] At least 3 checks with valid `mode`/`severity` and non-trivial "
        "`technique` text\n"
        "- [ ] Mutations are mappings, not bare strings\n"
        "- [ ] References section cites at least 1 external source\n\n"
        "## References\n\n"
        f"{references}\n"
    )
    return page_name, frontmatter + body


class ArmoryResearchBot(BaseBot):
    """Consumes armory gap findings and files de-duplicated factory tasks."""

    name = "armory-research"
    pauses_on_anthropic_block = False  # the research module runs its own models

    def __init__(
        self,
        interval_seconds: int | None = None,
        sources: str | None = None,
        max_tasks_per_run: int | None = None,
        armory_repo: str | None = None,
        research_cmd: str | None = None,
    ) -> None:
        super().__init__()
        settings = get_settings()
        self.interval_seconds = (
            interval_seconds
            if interval_seconds is not None
            else settings.armory_research_interval_seconds
        )
        self._sources = (
            sources if sources is not None else settings.armory_research_sources
        )
        self._max_tasks = (
            max_tasks_per_run
            if max_tasks_per_run is not None
            else settings.armory_research_max_tasks_per_run
        )
        self._armory_repo = (
            armory_repo
            if armory_repo is not None
            else (settings.armory_repo or "jyrkihuhta/molly-armory")
        )
        self._research_cmd = (
            research_cmd if research_cmd is not None else settings.armory_research_cmd
        )

    async def run(self) -> BotResult:
        started = time.monotonic()
        errors: list[str] = []

        try:
            findings = await self._fetch_findings()
        except Exception as e:
            return BotResult(
                ran_at=started,
                actions_taken=0,
                errors=[f"fetch findings: {type(e).__name__}: {e}"],
                details="research module invocation failed",
            )

        valid = [f for f in findings if self._is_valid(f)]
        dropped = len(findings) - len(valid)

        try:
            open_paths = await self._open_artifact_paths()
        except Exception as e:
            return BotResult(
                ran_at=started,
                actions_taken=0,
                errors=[f"list open tasks: {type(e).__name__}: {e}"],
                details=f"findings={len(findings)} valid={len(valid)}",
            )

        # Dedup on the stable artifact_path, then cap per run.
        fresh: list[dict] = []
        seen: set[str] = set()
        for f in valid:
            path = f["artifact_path"]
            if path in open_paths or path in seen:
                continue
            seen.add(path)
            fresh.append(f)
        capped = fresh[: self._max_tasks]

        actions = 0
        for f in capped:
            page_name, content = _render_task_page(f, self._armory_repo)
            try:
                async with MeshWikiClient() as wiki:
                    # Belt-and-suspenders: the stable page name means a stray
                    # existing page (e.g. a non-open leftover) is not re-created.
                    if await wiki.get_page(page_name) is not None:
                        continue
                    await wiki.create_page(page_name, content)
                actions += 1
                logger.info(
                    "armory-research: filed %s (class=%s path=%s)",
                    page_name,
                    f["vuln_class"],
                    f["artifact_path"],
                )
            except Exception as e:
                errors.append(f"create {page_name}: {type(e).__name__}: {e}")

        elapsed = time.monotonic() - started
        return BotResult(
            ran_at=started,
            actions_taken=actions,
            errors=errors,
            details=(
                f"findings={len(findings)} invalid={dropped} "
                f"open={len(open_paths)} fresh={len(fresh)} "
                f"filed={actions} capped_at={self._max_tasks} "
                f"elapsed={elapsed:.2f}s"
            ),
        )

    @staticmethod
    def _is_valid(finding: Any) -> bool:
        return isinstance(finding, dict) and all(finding.get(k) for k in _REQUIRED_KEYS)

    async def _open_artifact_paths(self) -> set[str]:
        """Collect artifact_path values of all currently-open factory tasks.

        Reads the ``playbook_path`` frontmatter field this bot writes, so dedup
        keys on the stable artifact path rather than the page name.
        """
        paths: set[str] = set()
        async with MeshWikiClient() as wiki:
            for status in _OPEN_STATUSES:
                for t in await wiki.list_tasks(status=status, assignee="factory"):
                    meta = t.get("metadata") or {}
                    path = meta.get("playbook_path")
                    if path:
                        paths.add(path)
        return paths

    async def _fetch_findings(self) -> list[dict]:
        """Pull findings from Molly's research module (transport-isolated).

        Default transport: run the configured command, which emits a JSON array
        of findings on stdout. Runs as a subprocess so it never blocks the event
        loop. Override this method (or ``armory_research_cmd``) to switch to a
        fetched-artifact transport without changing the bot logic.
        """
        argv = shlex.split(self._research_cmd) + [
            "--sources",
            self._sources,
            "--format",
            "json",
        ]
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        try:
            out, err = await asyncio.wait_for(proc.communicate(), timeout=300)
        except asyncio.TimeoutError:
            proc.kill()
            raise RuntimeError("research module timed out after 300s") from None
        if proc.returncode != 0:
            raise RuntimeError(
                f"research module exited {proc.returncode}: "
                f"{err.decode('utf-8', 'replace')[:300]}"
            )
        data = json.loads(out.decode("utf-8"))
        # Frozen contract: a JSON object {"findings": [...]} (an optional
        # sibling "unmapped" array is triage-only and ignored here).
        if not isinstance(data, dict) or not isinstance(data.get("findings"), list):
            raise RuntimeError('research module did not emit {"findings": [...]}')
        return data["findings"]
